// ============================================================
//  Teacher Module — Mock Data
//  15 realistic Bangladeshi teacher profiles
// ============================================================

import type { Teacher } from './types'

// ── Reference Data for dropdowns ──────────────────────────
export const MOCK_CLASSES = [
  { id: 'cls-1',  name: 'Class 1' },
  { id: 'cls-2',  name: 'Class 2' },
  { id: 'cls-3',  name: 'Class 3' },
  { id: 'cls-4',  name: 'Class 4' },
  { id: 'cls-5',  name: 'Class 5' },
  { id: 'cls-6',  name: 'Class 6' },
  { id: 'cls-7',  name: 'Class 7' },
  { id: 'cls-8',  name: 'Class 8' },
  { id: 'cls-9',  name: 'Class 9' },
  { id: 'cls-10', name: 'Class 10' },
  { id: 'cls-11', name: 'Class 11' },
  { id: 'cls-12', name: 'Class 12' },
]

export const MOCK_SECTIONS = [
  { id: 'sec-a', name: 'A' },
  { id: 'sec-b', name: 'B' },
  { id: 'sec-c', name: 'C' },
]

// BD Curriculum subjects — Class 1-12
export const MOCK_SUBJECTS = [
  // ── Primary (Class 1–4): simple combined subjects ─────────────────────────
  { id: 'sub-bangla-p',    name: 'বাংলা',                   classes: ['cls-1','cls-2','cls-3','cls-4'] },
  { id: 'sub-english-p',   name: 'English',                  classes: ['cls-1','cls-2','cls-3','cls-4'] },
  { id: 'sub-math-p',      name: 'গণিত',                    classes: ['cls-1','cls-2','cls-3','cls-4'] },
  { id: 'sub-science-p',   name: 'বিজ্ঞান',                 classes: ['cls-1','cls-2','cls-3','cls-4'] },
  { id: 'sub-env-p',       name: 'পরিবেশ পরিচিতি',          classes: ['cls-1','cls-2','cls-3','cls-4'] },
  { id: 'sub-religion-p',  name: 'ধর্ম ও নৈতিক শিক্ষা',    classes: ['cls-1','cls-2','cls-3','cls-4'] },

  // ── Junior (Class 5–8): combined subject, no paper split ──────────────────
  { id: 'sub-bangla-j',    name: 'বাংলা',                   classes: ['cls-5','cls-6','cls-7','cls-8'] },
  { id: 'sub-english-j',   name: 'ইংরেজি',                  classes: ['cls-5','cls-6','cls-7','cls-8'] },
  { id: 'sub-math',        name: 'গণিত',                    classes: ['cls-5','cls-6','cls-7','cls-8','cls-9','cls-10'] },
  { id: 'sub-science',     name: 'বিজ্ঞান',                 classes: ['cls-5','cls-6','cls-7','cls-8'] },
  { id: 'sub-bd-world',    name: 'বাংলাদেশ ও বিশ্বপরিচয়',  classes: ['cls-5','cls-6','cls-7','cls-8'] },
  { id: 'sub-religion-j',  name: 'ধর্ম ও নৈতিক শিক্ষা',    classes: ['cls-5','cls-6','cls-7','cls-8'] },
  { id: 'sub-arts',        name: 'চারু ও কারুকলা',          classes: ['cls-5','cls-6','cls-7','cls-8'] },
  { id: 'sub-pe',          name: 'শারীরিক শিক্ষা',          classes: ['cls-5','cls-6','cls-7','cls-8','cls-9','cls-10'] },
  { id: 'sub-ict-j',       name: 'ICT',                      classes: ['cls-6','cls-7','cls-8'] },
  { id: 'sub-agri',        name: 'কৃষিশিক্ষা',              classes: ['cls-6','cls-7','cls-8','cls-9','cls-10'] },
  { id: 'sub-home-sci',    name: 'গার্হস্থ্য বিজ্ঞান',      classes: ['cls-6','cls-7','cls-8','cls-9','cls-10'] },

  // ── SSC (Class 9–10): paper-wise Bangla & English ─────────────────────────
  { id: 'sub-bangla-1',    name: 'বাংলা ১ম পত্র',           classes: ['cls-9','cls-10'] },
  { id: 'sub-bangla-2',    name: 'বাংলা ২য় পত্র',           classes: ['cls-9','cls-10'] },
  { id: 'sub-english-1',   name: 'English 1st Paper',        classes: ['cls-9','cls-10'] },
  { id: 'sub-english-2',   name: 'English 2nd Paper',        classes: ['cls-9','cls-10'] },
  { id: 'sub-religion-s',  name: 'ধর্ম ও নৈতিক শিক্ষা',    classes: ['cls-9','cls-10'] },
  { id: 'sub-ict-s',       name: 'ICT',                      classes: ['cls-9','cls-10'] },
  { id: 'sub-bd-studies',  name: 'বাংলাদেশ ও বিশ্বপরিচয়',  classes: ['cls-9','cls-10'] },
  // SSC Science
  { id: 'sub-physics',     name: 'পদার্থবিজ্ঞান',           classes: ['cls-9','cls-10'] },
  { id: 'sub-chemistry',   name: 'রসায়ন',                   classes: ['cls-9','cls-10'] },
  { id: 'sub-biology',     name: 'জীববিজ্ঞান',              classes: ['cls-9','cls-10'] },
  { id: 'sub-hi-math',     name: 'উচ্চতর গণিত',             classes: ['cls-9','cls-10'] },
  // SSC Commerce
  { id: 'sub-account',     name: 'হিসাববিজ্ঞান',            classes: ['cls-9','cls-10'] },
  { id: 'sub-biz',         name: 'ব্যবসায় উদ্যোগ',          classes: ['cls-9','cls-10'] },
  { id: 'sub-finance',     name: 'ফিন্যান্স ও ব্যাংকিং',    classes: ['cls-9','cls-10'] },
  // SSC Arts
  { id: 'sub-history',     name: 'ইতিহাস',                  classes: ['cls-9','cls-10'] },
  { id: 'sub-geo',         name: 'ভূগোল ও পরিবেশ',          classes: ['cls-9','cls-10'] },
  { id: 'sub-civics',      name: 'পৌরনীতি ও নাগরিকতা',      classes: ['cls-9','cls-10'] },

  // ── HSC (Class 11–12): paper-wise Bangla & English ────────────────────────
  { id: 'sub-bangla-h1',   name: 'বাংলা ১ম পত্র',           classes: ['cls-11','cls-12'] },
  { id: 'sub-bangla-h2',   name: 'বাংলা ২য় পত্র',           classes: ['cls-11','cls-12'] },
  { id: 'sub-english-h1',  name: 'English 1st Paper',        classes: ['cls-11','cls-12'] },
  { id: 'sub-english-h2',  name: 'English 2nd Paper',        classes: ['cls-11','cls-12'] },
  { id: 'sub-ict-h',       name: 'ICT',                      classes: ['cls-11','cls-12'] },
  { id: 'sub-religion-h',  name: 'ধর্ম ও নৈতিক শিক্ষা',    classes: ['cls-11','cls-12'] },
  // HSC Science
  { id: 'sub-physics-h1',  name: 'পদার্থবিজ্ঞান ১ম পত্র',  classes: ['cls-11','cls-12'] },
  { id: 'sub-physics-h2',  name: 'পদার্থবিজ্ঞান ২য় পত্র',  classes: ['cls-11','cls-12'] },
  { id: 'sub-chemistry-h1',name: 'রসায়ন ১ম পত্র',           classes: ['cls-11','cls-12'] },
  { id: 'sub-chemistry-h2',name: 'রসায়ন ২য় পত্র',           classes: ['cls-11','cls-12'] },
  { id: 'sub-biology-h1',  name: 'জীববিজ্ঞান ১ম পত্র',     classes: ['cls-11','cls-12'] },
  { id: 'sub-biology-h2',  name: 'জীববিজ্ঞান ২য় পত্র',     classes: ['cls-11','cls-12'] },
  { id: 'sub-hi-math-h1',  name: 'উচ্চতর গণিত ১ম পত্র',    classes: ['cls-11','cls-12'] },
  { id: 'sub-hi-math-h2',  name: 'উচ্চতর গণিত ২য় পত্র',    classes: ['cls-11','cls-12'] },
  // HSC Commerce
  { id: 'sub-account-h1',  name: 'হিসাববিজ্ঞান ১ম পত্র',   classes: ['cls-11','cls-12'] },
  { id: 'sub-account-h2',  name: 'হিসাববিজ্ঞান ২য় পত্র',   classes: ['cls-11','cls-12'] },
  { id: 'sub-biz-org-h1',  name: 'ব্যবসায় সংগঠন ১ম পত্র',  classes: ['cls-11','cls-12'] },
  { id: 'sub-biz-org-h2',  name: 'ব্যবসায় সংগঠন ২য় পত্র',  classes: ['cls-11','cls-12'] },
  { id: 'sub-finance-h1',  name: 'ফিন্যান্স ১ম পত্র',       classes: ['cls-11','cls-12'] },
  { id: 'sub-finance-h2',  name: 'ফিন্যান্স ২য় পত্র',       classes: ['cls-11','cls-12'] },
  // HSC Arts
  { id: 'sub-history-h1',  name: 'ইতিহাস ১ম পত্র',          classes: ['cls-11','cls-12'] },
  { id: 'sub-history-h2',  name: 'ইতিহাস ২য় পত্র',          classes: ['cls-11','cls-12'] },
  { id: 'sub-civics-h1',   name: 'পৌরনীতি ১ম পত্র',         classes: ['cls-11','cls-12'] },
  { id: 'sub-civics-h2',   name: 'পৌরনীতি ২য় পত্র',         classes: ['cls-11','cls-12'] },
  { id: 'sub-econ-h1',     name: 'অর্থনীতি ১ম পত্র',         classes: ['cls-11','cls-12'] },
  { id: 'sub-econ-h2',     name: 'অর্থনীতি ২য় পত্র',         classes: ['cls-11','cls-12'] },
  { id: 'sub-geo-h1',      name: 'ভূগোল ১ম পত্র',            classes: ['cls-11','cls-12'] },
  { id: 'sub-geo-h2',      name: 'ভূগোল ২য় পত্র',            classes: ['cls-11','cls-12'] },
  { id: 'sub-islam-hist',  name: 'ইসলামের ইতিহাস ও সংস্কৃতি', classes: ['cls-11','cls-12'] },
]

// ── Mock Teacher Data ─────────────────────────────────────
export const MOCK_TEACHERS: Teacher[] = [
  {
    id: '1',
    createdAt: '2021-01-15T08:00:00Z',
    updatedAt: '2024-06-10T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2021-001',
    employeeId: 'EMP-001',
    fullName: 'Md. Shafiqul Islam',
    firstName: 'Shafiqul',
    lastName: 'Islam',
    nameBangla: 'মো. শফিকুল ইসলাম',
    gender: 'MALE',
    dateOfBirth: '1978-03-12',
    bloodGroup: 'B+',
    nationality: 'Bangladeshi',
    nidNumber: '1234567890123',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01711-123456',
    alternativePhone: '01611-123456',
    email: 'shafiqul@school.edu.bd',
    whatsapp: '01711-123456',
    presentAddress: '15/A, Mirpur-10, Dhaka',
    permanentAddress: 'Vill: Shalda, P.O: Bakerganj, Barisal',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Mirpur',
    area: 'Mirpur-10',
    postalCode: '1216',
    joiningDate: '2021-01-15',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'SENIOR_TEACHER',
    department: 'MATHEMATICS',
    qualifications: [
      { id: 'q1', degree: 'M.Sc.', subject: 'Mathematics', institution: 'Dhaka University', university: 'University of Dhaka', result: 'First Class', passingYear: 2002 },
      { id: 'q2', degree: 'B.Sc. (Hons)', subject: 'Mathematics', institution: 'Dhaka University', university: 'University of Dhaka', result: 'First Class', passingYear: 2000 },
    ],
    certifications: [{ id: 'c1', name: 'B.Ed.', issuer: 'National University', year: 2005 }],
    specialization: 'Higher Mathematics, Trigonometry',
    teachingSubjects: ['গণিত', 'উচ্চতর গণিত'],
    teachingLevels: ['SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [{ id: 'e1', organization: 'Bakerganj High School', designation: 'Assistant Teacher', fromYear: 2002, toYear: 2020, duration: '18 years' }],
    assignments: [
      { id: 'a1', academicYear: '2024', classId: 'cls-9', className: 'Class 9', sectionId: 'sec-a', sectionName: 'A', subjectId: 'sub-math', subjectName: 'গণিত', assignmentType: 'PRIMARY', isClassTeacher: true },
      { id: 'a2', academicYear: '2024', classId: 'cls-10', className: 'Class 10', sectionId: 'sec-a', sectionName: 'A', subjectId: 'sub-hi-math', subjectName: 'উচ্চতর গণিত', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [
      { id: 't1', name: 'Advanced Math Pedagogy', provider: 'NAPE Bangladesh', category: 'PEDAGOGY', startDate: '2022-06-01', endDate: '2022-06-07', duration: '7 days' },
    ],
    documents: [
      { id: 'd1', type: 'NID', name: 'National ID Card', url: '#', uploadedAt: '2021-01-15T08:00:00Z' },
    ],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    lastLogin: '2024-07-30T09:15:00Z',
    username: 'shafiqul.islam',
    loginEmail: 'shafiqul@school.edu.bd',
  },
  {
    id: '2',
    createdAt: '2020-08-20T08:00:00Z',
    updatedAt: '2024-05-15T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2020-001',
    employeeId: 'EMP-002',
    fullName: 'Nusrat Jahan Mitu',
    firstName: 'Nusrat',
    lastName: 'Jahan',
    nameBangla: 'নুসরাত জাহান মিতু',
    gender: 'FEMALE',
    dateOfBirth: '1985-07-22',
    bloodGroup: 'O+',
    nationality: 'Bangladeshi',
    nidNumber: '9876543210987',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01822-234567',
    email: 'nusrat@school.edu.bd',
    whatsapp: '01822-234567',
    presentAddress: '22/B, Dhanmondi R/A, Dhaka-1209',
    permanentAddress: '22/B, Dhanmondi R/A, Dhaka-1209',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Dhanmondi',
    postalCode: '1209',
    joiningDate: '2020-08-20',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'SENIOR_TEACHER',
    department: 'ENGLISH',
    qualifications: [
      { id: 'q3', degree: 'M.A.', subject: 'English Literature', institution: 'Jahangirnagar University', university: 'Jahangirnagar University', result: 'First Class', passingYear: 2008 },
      { id: 'q4', degree: 'B.A. (Hons)', subject: 'English', institution: 'Jahangirnagar University', university: 'Jahangirnagar University', result: 'First Class', passingYear: 2006 },
    ],
    certifications: [
      { id: 'c2', name: 'B.Ed.', issuer: 'National University', year: 2010 },
      { id: 'c3', name: 'IELTS', issuer: 'British Council', year: 2012 },
    ],
    specialization: 'English Grammar, Literature, Communication Skills',
    teachingSubjects: ['ইংরেজি'],
    teachingLevels: ['JUNIOR_SECONDARY', 'SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [{ id: 'e2', organization: 'Maple Leaf International School', designation: 'English Teacher', fromYear: 2008, toYear: 2020, duration: '12 years' }],
    assignments: [
      { id: 'a3', academicYear: '2024', classId: 'cls-11', className: 'Class 11', sectionId: 'sec-a', sectionName: 'A', subjectId: 'sub-english', subjectName: 'ইংরেজি', assignmentType: 'PRIMARY', isClassTeacher: true },
      { id: 'a4', academicYear: '2024', classId: 'cls-12', className: 'Class 12', subjectId: 'sub-english', subjectName: 'ইংরেজি', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [
      { id: 't2', name: 'Communicative Language Teaching', provider: 'British Council Bangladesh', category: 'PEDAGOGY', startDate: '2023-03-10', endDate: '2023-03-14', duration: '5 days' },
    ],
    documents: [{ id: 'd2', type: 'NID', name: 'National ID', url: '#', uploadedAt: '2020-08-20T08:00:00Z' }],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    lastLogin: '2024-07-29T08:30:00Z',
    username: 'nusrat.jahan',
    loginEmail: 'nusrat@school.edu.bd',
  },
  {
    id: '3',
    createdAt: '2018-01-10T08:00:00Z',
    updatedAt: '2024-07-01T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2018-001',
    employeeId: 'EMP-003',
    fullName: 'Aminur Rahman',
    firstName: 'Aminur',
    lastName: 'Rahman',
    nameBangla: 'আমিনুর রহমান',
    gender: 'MALE',
    dateOfBirth: '1975-11-05',
    bloodGroup: 'A+',
    nationality: 'Bangladeshi',
    nidNumber: '5678901234567',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01933-345678',
    email: 'aminur@school.edu.bd',
    presentAddress: '45, Green Road, Farmgate, Dhaka',
    permanentAddress: 'Vill: Amtali, Dist: Barguna, Barisal',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Tejgaon',
    postalCode: '1215',
    joiningDate: '2018-01-10',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ON_LEAVE',
    designation: 'SENIOR_TEACHER',
    department: 'PHYSICS',
    qualifications: [
      { id: 'q5', degree: 'M.Sc.', subject: 'Physics', institution: 'BUET', university: 'Bangladesh University of Engineering & Technology', result: '3.8/4.0 CGPA', passingYear: 1999 },
    ],
    certifications: [{ id: 'c4', name: 'B.Ed.', issuer: 'National University', year: 2002 }],
    specialization: 'Classical Mechanics, Electromagnetism',
    teachingSubjects: ['পদার্থবিজ্ঞান', 'বিজ্ঞান'],
    teachingLevels: ['SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [],
    assignments: [
      { id: 'a5', academicYear: '2024', classId: 'cls-9', className: 'Class 9', subjectId: 'sub-physics', subjectName: 'পদার্থবিজ্ঞান', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [],
    documents: [],
    accountStatus: 'INACTIVE',
    role: 'ASSISTANT_TEACHER',
    username: 'aminur.rahman',
  },
  {
    id: '4',
    createdAt: '2015-07-01T08:00:00Z',
    updatedAt: '2024-07-15T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2015-001',
    employeeId: 'EMP-004',
    fullName: 'Dr. Farida Begum',
    firstName: 'Farida',
    lastName: 'Begum',
    nameBangla: 'ডা. ফরিদা বেগম',
    gender: 'FEMALE',
    dateOfBirth: '1972-04-18',
    bloodGroup: 'AB+',
    nationality: 'Bangladeshi',
    nidNumber: '3456789012345',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01555-456789',
    alternativePhone: '01655-456789',
    email: 'farida@school.edu.bd',
    whatsapp: '01555-456789',
    presentAddress: 'House 12, Road 3, Uttara Sector 4, Dhaka',
    permanentAddress: 'House 12, Road 3, Uttara Sector 4, Dhaka',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Uttara',
    postalCode: '1230',
    joiningDate: '2015-07-01',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'VICE_PRINCIPAL',
    department: 'BIOLOGY',
    qualifications: [
      { id: 'q6', degree: 'Ph.D.', subject: 'Botany', institution: 'Dhaka University', university: 'University of Dhaka', result: 'Excellent', passingYear: 2005 },
      { id: 'q7', degree: 'M.Sc.', subject: 'Biology', institution: 'Dhaka University', university: 'University of Dhaka', result: 'First Class', passingYear: 1997 },
    ],
    certifications: [
      { id: 'c5', name: 'B.Ed.', issuer: 'National University', year: 2000 },
      { id: 'c6', name: 'M.Ed.', issuer: 'Dhaka University', year: 2010 },
    ],
    specialization: 'Botany, Zoology, Cell Biology',
    teachingSubjects: ['জীববিজ্ঞান', 'বিজ্ঞান'],
    teachingLevels: ['SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [{ id: 'e3', organization: 'Viqarunnisa Noon School & College', designation: 'Senior Lecturer', fromYear: 2000, toYear: 2015, duration: '15 years' }],
    assignments: [
      { id: 'a6', academicYear: '2024', classId: 'cls-11', className: 'Class 11', subjectId: 'sub-biology', subjectName: 'জীববিজ্ঞান', assignmentType: 'PRIMARY', isClassTeacher: false },
      { id: 'a7', academicYear: '2024', classId: 'cls-12', className: 'Class 12', subjectId: 'sub-biology', subjectName: 'জীববিজ্ঞান', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [
      { id: 't3', name: 'STEM Education Leadership', provider: 'USAID Bangladesh', category: 'MANAGEMENT', startDate: '2023-09-01', endDate: '2023-09-05', duration: '5 days', certificateUrl: '#' },
    ],
    documents: [
      { id: 'd3', type: 'DEGREE_CERT', name: 'PhD Certificate', url: '#', uploadedAt: '2015-07-01T08:00:00Z' },
      { id: 'd4', type: 'NID', name: 'NID Card', url: '#', uploadedAt: '2015-07-01T08:00:00Z' },
    ],
    accountStatus: 'ACTIVE',
    role: 'HEAD_TEACHER',
    lastLogin: '2024-07-31T07:00:00Z',
    username: 'farida.begum',
    loginEmail: 'farida@school.edu.bd',
  },
  {
    id: '5',
    createdAt: '2022-03-01T08:00:00Z',
    updatedAt: '2024-07-20T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2022-001',
    employeeId: 'EMP-005',
    fullName: 'Md. Jamal Uddin',
    firstName: 'Jamal',
    lastName: 'Uddin',
    nameBangla: 'মো. জামাল উদ্দিন',
    gender: 'MALE',
    dateOfBirth: '1990-06-30',
    bloodGroup: 'B-',
    nationality: 'Bangladeshi',
    nidNumber: '2345678901234',
    maritalStatus: 'SINGLE',
    religion: 'ISLAM',
    phone: '01788-567890',
    email: 'jamal@school.edu.bd',
    presentAddress: 'Flat 4B, House 55, Banani, Dhaka',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Banani',
    postalCode: '1213',
    joiningDate: '2022-03-01',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'ICT_TEACHER',
    department: 'ICT',
    qualifications: [
      { id: 'q8', degree: 'B.Sc.', subject: 'Computer Science', institution: 'BRAC University', university: 'BRAC University', result: '3.6/4.0 CGPA', passingYear: 2014 },
    ],
    certifications: [
      { id: 'c7', name: 'Oracle Certified Associate', issuer: 'Oracle', year: 2016 },
      { id: 'c8', name: 'B.Ed.', issuer: 'National University', year: 2018 },
    ],
    specialization: 'Web Development, Programming, Database',
    teachingSubjects: ['ICT'],
    teachingLevels: ['JUNIOR_SECONDARY', 'SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [{ id: 'e4', organization: 'IPDC Finance Ltd.', designation: 'Junior Software Engineer', fromYear: 2014, toYear: 2022, duration: '8 years' }],
    assignments: [
      { id: 'a8', academicYear: '2024', classId: 'cls-8', className: 'Class 8', subjectId: 'sub-ict', subjectName: 'ICT', assignmentType: 'PRIMARY', isClassTeacher: true },
      { id: 'a9', academicYear: '2024', classId: 'cls-9', className: 'Class 9', subjectId: 'sub-ict', subjectName: 'ICT', assignmentType: 'PRIMARY', isClassTeacher: false },
      { id: 'a10', academicYear: '2024', classId: 'cls-10', className: 'Class 10', subjectId: 'sub-ict', subjectName: 'ICT', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [
      { id: 't4', name: 'Digital Classroom Training', provider: 'a2i Bangladesh', category: 'TECHNOLOGY', startDate: '2023-01-15', endDate: '2023-01-19', duration: '5 days', certificateUrl: '#' },
    ],
    documents: [],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    lastLogin: '2024-07-30T11:00:00Z',
    username: 'jamal.uddin',
    loginEmail: 'jamal@school.edu.bd',
  },
  {
    id: '6',
    createdAt: '2010-01-01T08:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2010-001',
    employeeId: 'EMP-006',
    fullName: 'Md. Rafiqul Islam Khan',
    firstName: 'Rafiqul',
    lastName: 'Khan',
    nameBangla: 'মো. রফিকুল ইসলাম খান',
    gender: 'MALE',
    dateOfBirth: '1965-02-14',
    bloodGroup: 'O-',
    nationality: 'Bangladeshi',
    nidNumber: '6789012345678',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01611-678901',
    alternativePhone: '01711-678901',
    email: 'rafiqul@school.edu.bd',
    presentAddress: 'House 1, Road 1, Dhanmondi-2, Dhaka',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Dhanmondi',
    postalCode: '1205',
    joiningDate: '2010-01-01',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'PRINCIPAL',
    department: 'BANGLA',
    qualifications: [
      { id: 'q9', degree: 'M.A.', subject: 'Bangla Literature', institution: 'Rajshahi University', university: 'University of Rajshahi', result: 'First Class', passingYear: 1990 },
      { id: 'q10', degree: 'M.Ed.', subject: 'Education', institution: 'NAEM', university: 'Dhaka University', result: 'First Class', passingYear: 2000 },
    ],
    certifications: [{ id: 'c9', name: 'B.Ed.', issuer: 'National University', year: 1993 }],
    specialization: 'Bangla Language, Bengali Literature, School Administration',
    teachingSubjects: ['বাংলা'],
    teachingLevels: ['SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [{ id: 'e5', organization: 'Rajshahi Collegiate School', designation: 'Head Teacher', fromYear: 1990, toYear: 2010, duration: '20 years' }],
    assignments: [
      { id: 'a11', academicYear: '2024', classId: 'cls-12', className: 'Class 12', subjectId: 'sub-bangla', subjectName: 'বাংলা', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [
      { id: 't5', name: 'School Leadership & Management', provider: 'BANBEIS', category: 'MANAGEMENT', startDate: '2022-11-01', endDate: '2022-11-10', duration: '10 days', certificateUrl: '#' },
    ],
    documents: [
      { id: 'd5', type: 'NID', name: 'NID Card', url: '#', uploadedAt: '2010-01-01T08:00:00Z' },
      { id: 'd6', type: 'DEGREE_CERT', name: 'M.Ed. Certificate', url: '#', uploadedAt: '2010-01-01T08:00:00Z' },
    ],
    accountStatus: 'ACTIVE',
    role: 'ADMIN',
    lastLogin: '2024-07-31T08:00:00Z',
    username: 'principal.rafiqul',
    loginEmail: 'rafiqul@school.edu.bd',
  },
  {
    id: '7',
    createdAt: '2023-01-05T08:00:00Z',
    updatedAt: '2024-07-01T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2023-001',
    employeeId: 'EMP-007',
    fullName: 'Sumaiya Akter',
    firstName: 'Sumaiya',
    lastName: 'Akter',
    nameBangla: 'সুমাইয়া আক্তার',
    gender: 'FEMALE',
    dateOfBirth: '1993-09-15',
    bloodGroup: 'A-',
    nationality: 'Bangladeshi',
    maritalStatus: 'SINGLE',
    religion: 'ISLAM',
    phone: '01977-789012',
    email: 'sumaiya@school.edu.bd',
    presentAddress: '88, Mohammadpur, Dhaka-1207',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Mohammadpur',
    postalCode: '1207',
    joiningDate: '2023-01-05',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'JUNIOR_TEACHER',
    department: 'CHEMISTRY',
    qualifications: [
      { id: 'q11', degree: 'M.Sc.', subject: 'Chemistry', institution: 'Chittagong University', university: 'University of Chittagong', result: '3.5/4.0 CGPA', passingYear: 2018 },
    ],
    certifications: [{ id: 'c10', name: 'B.Ed.', issuer: 'National University', year: 2020 }],
    specialization: 'Organic Chemistry, Inorganic Chemistry',
    teachingSubjects: ['রসায়ন', 'বিজ্ঞান'],
    teachingLevels: ['SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [],
    assignments: [
      { id: 'a12', academicYear: '2024', classId: 'cls-10', className: 'Class 10', subjectId: 'sub-chemistry', subjectName: 'রসায়ন', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [],
    documents: [],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    username: 'sumaiya.akter',
  },
  {
    id: '8',
    createdAt: '2019-06-01T08:00:00Z',
    updatedAt: '2024-07-10T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2019-001',
    employeeId: 'EMP-008',
    fullName: 'Md. Kamal Hossain',
    firstName: 'Kamal',
    lastName: 'Hossain',
    nameBangla: 'মো. কামাল হোসেন',
    gender: 'MALE',
    dateOfBirth: '1982-12-01',
    bloodGroup: 'AB-',
    nationality: 'Bangladeshi',
    nidNumber: '8901234567890',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01812-890123',
    email: 'kamal@school.edu.bd',
    presentAddress: 'Bashabo, Sabujbagh, Dhaka-1214',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Sabujbagh',
    postalCode: '1214',
    joiningDate: '2019-06-01',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'ASSISTANT_TEACHER',
    department: 'HISTORY',
    qualifications: [
      { id: 'q12', degree: 'M.A.', subject: 'History', institution: 'Jahangirnagar University', university: 'Jahangirnagar University', result: 'Second Class', passingYear: 2006 },
    ],
    certifications: [{ id: 'c11', name: 'B.Ed.', issuer: 'National University', year: 2008 }],
    specialization: 'Bangladesh History, World History',
    teachingSubjects: ['ইতিহাস', 'বাংলাদেশ ও বিশ্বপরিচয়'],
    teachingLevels: ['JUNIOR_SECONDARY', 'SECONDARY'],
    previousExperience: [{ id: 'e6', organization: 'Ideal School & College', designation: 'Teacher', fromYear: 2006, toYear: 2019, duration: '13 years' }],
    assignments: [
      { id: 'a13', academicYear: '2024', classId: 'cls-7', className: 'Class 7', subjectId: 'sub-bd-world', subjectName: 'বাংলাদেশ ও বিশ্বপরিচয়', assignmentType: 'PRIMARY', isClassTeacher: true },
      { id: 'a14', academicYear: '2024', classId: 'cls-9', className: 'Class 9', subjectId: 'sub-history', subjectName: 'ইতিহাস', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [],
    documents: [],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    username: 'kamal.hossain',
  },
  {
    id: '9',
    createdAt: '2021-09-01T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2021-002',
    employeeId: 'EMP-009',
    fullName: 'Rashida Khanam',
    firstName: 'Rashida',
    lastName: 'Khanam',
    nameBangla: 'রাশিদা খানম',
    gender: 'FEMALE',
    dateOfBirth: '1988-03-25',
    bloodGroup: 'B+',
    nationality: 'Bangladeshi',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01999-901234',
    email: 'rashida@school.edu.bd',
    presentAddress: 'Kazipara, Mirpur-10, Dhaka',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Mirpur',
    postalCode: '1216',
    joiningDate: '2021-09-01',
    teacherCategory: 'REGULAR',
    employmentType: 'PART_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'ASSISTANT_TEACHER',
    department: 'ACCOUNTING',
    qualifications: [
      { id: 'q13', degree: 'M.Com.', subject: 'Accounting', institution: 'Dhaka University', university: 'University of Dhaka', result: 'Second Class', passingYear: 2012 },
    ],
    certifications: [],
    specialization: 'Financial Accounting, Cost Accounting',
    teachingSubjects: ['হিসাববিজ্ঞান'],
    teachingLevels: ['SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [],
    assignments: [
      { id: 'a15', academicYear: '2024', classId: 'cls-9', className: 'Class 9', subjectId: 'sub-account', subjectName: 'হিসাববিজ্ঞান', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [],
    documents: [],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    username: 'rashida.khanam',
  },
  {
    id: '10',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-07-28T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2024-001',
    employeeId: 'EMP-010',
    fullName: 'Sabbir Ahmed',
    firstName: 'Sabbir',
    lastName: 'Ahmed',
    nameBangla: 'সাব্বির আহমেদ',
    gender: 'MALE',
    dateOfBirth: '1995-05-10',
    bloodGroup: 'O+',
    nationality: 'Bangladeshi',
    maritalStatus: 'SINGLE',
    religion: 'ISLAM',
    phone: '01633-012345',
    email: 'sabbir@school.edu.bd',
    presentAddress: 'East Rayer Bazar, Dhaka-1209',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Dhanmondi',
    postalCode: '1209',
    joiningDate: '2024-01-15',
    teacherCategory: 'REGULAR',
    employmentType: 'CONTRACTUAL',
    employmentStatus: 'ACTIVE',
    designation: 'JUNIOR_TEACHER',
    department: 'BANGLA',
    qualifications: [
      { id: 'q14', degree: 'M.A.', subject: 'Bangla', institution: 'Eden University College', university: 'National University', result: 'Second Class', passingYear: 2020 },
    ],
    certifications: [],
    specialization: 'Bangla Grammar, Creative Writing',
    teachingSubjects: ['বাংলা'],
    teachingLevels: ['PRIMARY', 'JUNIOR_SECONDARY'],
    previousExperience: [],
    assignments: [
      { id: 'a16', academicYear: '2024', classId: 'cls-5', className: 'Class 5', subjectId: 'sub-bangla', subjectName: 'বাংলা', assignmentType: 'PRIMARY', isClassTeacher: true },
      { id: 'a17', academicYear: '2024', classId: 'cls-6', className: 'Class 6', subjectId: 'sub-bangla', subjectName: 'বাংলা', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [],
    documents: [],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    username: 'sabbir.ahmed',
  },
  {
    id: '11',
    createdAt: '2017-08-01T08:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2017-001',
    employeeId: 'EMP-011',
    fullName: 'Tariqul Islam Bhuiyan',
    firstName: 'Tariqul',
    lastName: 'Bhuiyan',
    nameBangla: 'তারিকুল ইসলাম ভূঁইয়া',
    gender: 'MALE',
    dateOfBirth: '1980-08-20',
    bloodGroup: 'A+',
    nationality: 'Bangladeshi',
    nidNumber: '7890123456789',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01766-234567',
    email: 'tariqul@school.edu.bd',
    presentAddress: 'Khilgaon, Dhaka-1219',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Khilgaon',
    postalCode: '1219',
    joiningDate: '2017-08-01',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'LAB_TEACHER',
    department: 'CHEMISTRY',
    qualifications: [
      { id: 'q15', degree: 'M.Sc.', subject: 'Chemistry', institution: 'Shahjalal University', university: 'Shahjalal University of Sci & Tech', result: 'First Class', passingYear: 2005 },
    ],
    certifications: [{ id: 'c12', name: 'Lab Management Certificate', issuer: 'BCSIR', year: 2010 }],
    specialization: 'Laboratory Management, Practical Chemistry',
    teachingSubjects: ['রসায়ন', 'পদার্থবিজ্ঞান'],
    teachingLevels: ['SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [],
    assignments: [
      { id: 'a18', academicYear: '2024', classId: 'cls-9', className: 'Class 9', subjectId: 'sub-chemistry', subjectName: 'রসায়ন', assignmentType: 'SECONDARY', isClassTeacher: false },
      { id: 'a19', academicYear: '2024', classId: 'cls-10', className: 'Class 10', subjectId: 'sub-chemistry', subjectName: 'রসায়ন', assignmentType: 'SECONDARY', isClassTeacher: false },
    ],
    trainings: [],
    documents: [],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    username: 'tariqul.bhuiyan',
  },
  {
    id: '12',
    createdAt: '2020-01-10T08:00:00Z',
    updatedAt: '2024-07-20T10:00:00Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    isActive: true,
    teacherId: 'TCH-2020-002',
    employeeId: 'EMP-012',
    fullName: 'Mahmuda Sultana',
    firstName: 'Mahmuda',
    lastName: 'Sultana',
    nameBangla: 'মাহমুদা সুলতানা',
    gender: 'FEMALE',
    dateOfBirth: '1983-01-07',
    bloodGroup: 'B+',
    nationality: 'Bangladeshi',
    nidNumber: '0123456789012',
    maritalStatus: 'MARRIED',
    religion: 'ISLAM',
    phone: '01866-345678',
    email: 'mahmuda@school.edu.bd',
    presentAddress: 'Badda, Dhaka-1212',
    division: 'DHAKA',
    district: 'Dhaka',
    upazila: 'Badda',
    postalCode: '1212',
    joiningDate: '2020-01-10',
    teacherCategory: 'REGULAR',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    designation: 'ASSISTANT_TEACHER',
    department: 'ECONOMICS',
    qualifications: [
      { id: 'q16', degree: 'M.S.S.', subject: 'Economics', institution: 'Dhaka University', university: 'University of Dhaka', result: 'Second Class', passingYear: 2007 },
    ],
    certifications: [{ id: 'c13', name: 'B.Ed.', issuer: 'National University', year: 2010 }],
    specialization: 'Micro/Macro Economics, Finance',
    teachingSubjects: ['অর্থনীতি', 'পৌরনীতি'],
    teachingLevels: ['SECONDARY', 'HIGHER_SECONDARY'],
    previousExperience: [{ id: 'e7', organization: 'Shaheen School', designation: 'Assistant Teacher', fromYear: 2007, toYear: 2020, duration: '13 years' }],
    assignments: [
      { id: 'a20', academicYear: '2024', classId: 'cls-11', className: 'Class 11', subjectId: 'sub-econ', subjectName: 'অর্থনীতি', assignmentType: 'PRIMARY', isClassTeacher: false },
      { id: 'a21', academicYear: '2024', classId: 'cls-12', className: 'Class 12', subjectId: 'sub-econ', subjectName: 'অর্থনীতি', assignmentType: 'PRIMARY', isClassTeacher: false },
    ],
    trainings: [],
    documents: [],
    accountStatus: 'ACTIVE',
    role: 'ASSISTANT_TEACHER',
    username: 'mahmuda.sultana',
  },
]

