import type { FeeStructure, StudentWaiver, MonthlyBillingRun, PaymentRecord, ManualDue } from './types'

export const MOCK_FEE_STRUCTURES: FeeStructure[] = [
  {
    id: 'fs-cls-8',
    name: 'Class 8 Standard Monthly Fee Structure',
    target_type: 'CLASS',
    class_id: 'cls-8',
    batch_id: null,
    class_name: 'Class 8',
    batch_name: null,
    fee_items: [
      { id: 'fi-8-1', fee_type: 'TUITION', label: 'Monthly Tuition Fee', amount: 1300, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-8-2', fee_type: 'EXAM', label: 'Monthly Evaluation & Exam Fee', amount: 400, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-8-3', fee_type: 'LIBRARY', label: 'Library & Computer Lab Fee', amount: 150, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-8-4', fee_type: 'DEVELOPMENT', label: 'Campus Development Fee', amount: 150, frequency: 'MONTHLY', due_day: 10 },
    ],
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fs-cls-9',
    name: 'Class 9 Secondary Academic Structure',
    target_type: 'CLASS',
    class_id: 'cls-9',
    batch_id: null,
    class_name: 'Class 9',
    batch_name: null,
    fee_items: [
      { id: 'fi-9-1', fee_type: 'TUITION', label: 'Monthly Tuition Fee', amount: 1600, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-9-2', fee_type: 'EXAM', label: 'Term Assessment Fee', amount: 500, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-9-3', fee_type: 'DEVELOPMENT', label: 'Lab & Campus Maintenance', amount: 250, frequency: 'MONTHLY', due_day: 10 },
    ],
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fs-cls-10',
    name: 'Class 10 SSC Candidate Package',
    target_type: 'CLASS',
    class_id: 'cls-10',
    batch_id: null,
    class_name: 'Class 10',
    batch_name: null,
    fee_items: [
      { id: 'fi-10-1', fee_type: 'TUITION', label: 'Monthly Tuition & Coaching Fee', amount: 1800, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-10-2', fee_type: 'EXAM', label: 'Model Test & Test Paper Prep', amount: 700, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-10-3', fee_type: 'OTHER', label: 'Special Guide & Sheet Fee', amount: 300, frequency: 'MONTHLY', due_day: 10 },
    ],
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fs-cls-6',
    name: 'Class 6 Foundation Structure',
    target_type: 'CLASS',
    class_id: 'cls-6',
    batch_id: null,
    class_name: 'Class 6',
    batch_name: null,
    fee_items: [
      { id: 'fi-6-1', fee_type: 'TUITION', label: 'Monthly Tuition Fee', amount: 1100, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-6-2', fee_type: 'EXAM', label: 'Monthly Assessment Fee', amount: 300, frequency: 'MONTHLY', due_day: 10 },
    ],
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fs-cls-7',
    name: 'Class 7 Standard Fee Structure',
    target_type: 'CLASS',
    class_id: 'cls-7',
    batch_id: null,
    class_name: 'Class 7',
    batch_name: null,
    fee_items: [
      { id: 'fi-7-1', fee_type: 'TUITION', label: 'Monthly Tuition Fee', amount: 1200, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-7-2', fee_type: 'EXAM', label: 'Monthly Assessment Fee', amount: 350, frequency: 'MONTHLY', due_day: 10 },
      { id: 'fi-7-3', fee_type: 'LIBRARY', label: 'Library & Activity Fee', amount: 150, frequency: 'MONTHLY', due_day: 10 },
    ],
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
]

export const MOCK_STUDENT_WAIVERS: StudentWaiver[] = [
  {
    id: 'sw-1',
    student_id: 'std-8-01',
    student_name: 'Rahim Ahmed',
    roll_number: '01',
    class_name: 'Class 8',
    waiver_type: 'PERCENTAGE',
    value: 50,
    fee_type: 'TUITION',
    reason: 'Academic Merit Scholarship (Top 1 in class)',
    is_active: true,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'sw-2',
    student_id: 'std-8-04',
    student_name: 'Tanvir Hossain',
    roll_number: '04',
    class_name: 'Class 8',
    waiver_type: 'FIXED',
    value: 400,
    fee_type: 'ALL',
    reason: 'Sibling Concession (Brother studying in Class 10)',
    is_active: true,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'sw-3',
    student_id: 'std-8-07',
    student_name: 'Sadia Sultana',
    roll_number: '07',
    class_name: 'Class 8',
    waiver_type: 'PERCENTAGE',
    value: 100,
    fee_type: 'TUITION',
    reason: 'Full Free-Studentship (Special Quota)',
    is_active: true,
    created_at: '2026-02-01T00:00:00Z',
  },
]

export const MOCK_MONTHLY_BILLINGS: MonthlyBillingRun[] = [
  {
    id: 'mbr-2026-08-cls8',
    month: 8,
    year: 2026,
    target_type: 'CLASS',
    class_id: 'cls-8',
    class_name: 'Class 8',
    generated_count: 20,
    total_billed_amount: 40000,
    fee_structure_id: 'fs-cls-8',
    created_by: 'Admin',
    created_at: '2026-08-01T09:00:00Z',
  },
  {
    id: 'mbr-2026-07-cls8',
    month: 7,
    year: 2026,
    target_type: 'CLASS',
    class_id: 'cls-8',
    class_name: 'Class 8',
    generated_count: 20,
    total_billed_amount: 40000,
    fee_structure_id: 'fs-cls-8',
    created_by: 'Admin',
    created_at: '2026-07-01T09:00:00Z',
  },
]

const NOW = new Date()
const THIS_MONTH = NOW.getMonth() + 1
const THIS_YEAR  = NOW.getFullYear()

export const MOCK_PAYMENTS: PaymentRecord[] = [
  // Class 10 (cls-10)
  {
    id: 'pay-001',
    invoice_number: `INV-${THIS_YEAR}-0001`,
    student_id: '1',
    student_name: 'Rahim Uddin',
    roll_number: '01',
    class_id: 'cls-10',
    batch_id: null,
    class_name: 'Class 10',
    fee_structure_id: 'fs-cls-10',
    items: [
      { fee_type: 'TUITION', label: 'Monthly Tuition & Coaching Fee', amount: 1800, month: THIS_MONTH, year: THIS_YEAR },
      { fee_type: 'EXAM', label: 'Model Test & Test Paper Prep', amount: 700, month: THIS_MONTH, year: THIS_YEAR },
    ],
    subtotal: 2500,
    discount_amount: 0,
    waiver_reason: null,
    total_amount: 2500,
    payment_method: 'BKASH',
    transaction_id: 'TRX987654321',
    paid_at: new Date(THIS_YEAR, THIS_MONTH - 1, 5, 10, 30).toISOString(),
    collected_by: 'Admin Office',
    note: 'Paid via bKash online gateway',
    status: 'PAID',
    created_at: new Date(THIS_YEAR, THIS_MONTH - 1, 5, 10, 30).toISOString(),
    updated_at: new Date(THIS_YEAR, THIS_MONTH - 1, 5, 10, 30).toISOString(),
  },
  {
    id: 'pay-002',
    invoice_number: `INV-${THIS_YEAR}-0002`,
    student_id: '2',
    student_name: 'Sadia Islam',
    roll_number: '02',
    class_id: 'cls-10',
    batch_id: null,
    class_name: 'Class 10',
    fee_structure_id: 'fs-cls-10',
    items: [
      { fee_type: 'TUITION', label: 'Monthly Tuition & Coaching Fee', amount: 1800, month: THIS_MONTH, year: THIS_YEAR },
    ],
    subtotal: 1800,
    discount_amount: 0,
    waiver_reason: null,
    total_amount: 1800,
    payment_method: 'CASH',
    transaction_id: null,
    paid_at: new Date(THIS_YEAR, THIS_MONTH - 1, 7, 11, 15).toISOString(),
    collected_by: 'Accounts Desk',
    note: 'Cash received by accounts',
    status: 'PAID',
    created_at: new Date(THIS_YEAR, THIS_MONTH - 1, 7, 11, 15).toISOString(),
    updated_at: new Date(THIS_YEAR, THIS_MONTH - 1, 7, 11, 15).toISOString(),
  },
  {
    id: 'pay-003',
    invoice_number: `INV-${THIS_YEAR}-0003`,
    student_id: '22',
    student_name: 'Nusrat Jahan',
    roll_number: '05',
    class_id: 'cls-10',
    batch_id: null,
    class_name: 'Class 10',
    fee_structure_id: 'fs-cls-10',
    items: [
      { fee_type: 'TUITION', label: 'Monthly Tuition & Coaching Fee', amount: 1800, month: THIS_MONTH, year: THIS_YEAR },
    ],
    subtotal: 1800,
    discount_amount: 0,
    waiver_reason: null,
    total_amount: 1800,
    payment_method: 'NAGAD',
    transaction_id: 'NGD12345678',
    paid_at: new Date(THIS_YEAR, THIS_MONTH - 1, 8, 14, 20).toISOString(),
    collected_by: 'Accounts Desk',
    note: null,
    status: 'PAID',
    created_at: new Date(THIS_YEAR, THIS_MONTH - 1, 8, 14, 20).toISOString(),
    updated_at: new Date(THIS_YEAR, THIS_MONTH - 1, 8, 14, 20).toISOString(),
  },
  // Class 9 (cls-9)
  {
    id: 'pay-004',
    invoice_number: `INV-${THIS_YEAR}-0004`,
    student_id: '3',
    student_name: 'Abdur Rahim',
    roll_number: '01',
    class_id: 'cls-9',
    batch_id: null,
    class_name: 'Class 9',
    fee_structure_id: 'fs-cls-9',
    items: [
      { fee_type: 'TUITION', label: 'Monthly Tuition Fee', amount: 1600, month: THIS_MONTH, year: THIS_YEAR },
    ],
    subtotal: 1600,
    discount_amount: 0,
    waiver_reason: null,
    total_amount: 1600,
    payment_method: 'CASH',
    transaction_id: null,
    paid_at: new Date(THIS_YEAR, THIS_MONTH - 1, 6, 9, 45).toISOString(),
    collected_by: 'Admin Office',
    note: null,
    status: 'PAID',
    created_at: new Date(THIS_YEAR, THIS_MONTH - 1, 6, 9, 45).toISOString(),
    updated_at: new Date(THIS_YEAR, THIS_MONTH - 1, 6, 9, 45).toISOString(),
  },
  // Class 8 (cls-8)
  {
    id: 'pay-005',
    invoice_number: `INV-${THIS_YEAR}-0005`,
    student_id: '5',
    student_name: 'Mehedi Hasan',
    roll_number: '01',
    class_id: 'cls-8',
    batch_id: null,
    class_name: 'Class 8',
    fee_structure_id: 'fs-cls-8',
    items: [
      { fee_type: 'TUITION', label: 'Monthly Tuition Fee', amount: 1300, month: THIS_MONTH, year: THIS_YEAR },
      { fee_type: 'EXAM', label: 'Monthly Evaluation & Exam Fee', amount: 400, month: THIS_MONTH, year: THIS_YEAR },
    ],
    subtotal: 1700,
    discount_amount: 0,
    waiver_reason: null,
    total_amount: 1700,
    payment_method: 'BKASH',
    transaction_id: 'BKS77889900',
    paid_at: new Date(THIS_YEAR, THIS_MONTH - 1, 9, 16, 0).toISOString(),
    collected_by: 'Online System',
    note: null,
    status: 'PAID',
    created_at: new Date(THIS_YEAR, THIS_MONTH - 1, 9, 16, 0).toISOString(),
    updated_at: new Date(THIS_YEAR, THIS_MONTH - 1, 9, 16, 0).toISOString(),
  },
]

export const MOCK_MANUAL_DUES: ManualDue[] = [
  {
    id: 'due-001',
    student_id: '10',
    student_name: 'Sumaiya Begum',
    roll_number: '03',
    class_id: 'cls-10',
    batch_id: null,
    class_name: 'Class 10',
    fee_type: 'TUITION',
    label: 'Class 10 Monthly Tuition Fee',
    amount: 1800,
    month: THIS_MONTH,
    year: THIS_YEAR,
    due_date: `${THIS_YEAR}-${String(THIS_MONTH).padStart(2, '0')}-10`,
    note: 'Monthly billing due',
    is_paid: false,
    paid_payment_id: null,
    created_at: new Date(THIS_YEAR, THIS_MONTH - 1, 1).toISOString(),
    updated_at: new Date(THIS_YEAR, THIS_MONTH - 1, 1).toISOString(),
  },
  {
    id: 'due-002',
    student_id: '21',
    student_name: 'Tanvir Hasan',
    roll_number: '04',
    class_id: 'cls-10',
    batch_id: null,
    class_name: 'Class 10',
    fee_type: 'TUITION',
    label: 'Class 10 Monthly Tuition Fee',
    amount: 1800,
    month: THIS_MONTH,
    year: THIS_YEAR,
    due_date: `${THIS_YEAR}-${String(THIS_MONTH).padStart(2, '0')}-10`,
    note: 'Monthly billing due',
    is_paid: false,
    paid_payment_id: null,
    created_at: new Date(THIS_YEAR, THIS_MONTH - 1, 1).toISOString(),
    updated_at: new Date(THIS_YEAR, THIS_MONTH - 1, 1).toISOString(),
  },
  {
    id: 'due-003',
    student_id: '17',
    student_name: 'Mizanur Rahman',
    roll_number: '01',
    class_id: 'cls-10',
    batch_id: null,
    class_name: 'Class 10',
    fee_type: 'TUITION',
    label: 'Class 10 Commerce Tuition Fee',
    amount: 1800,
    month: THIS_MONTH,
    year: THIS_YEAR,
    due_date: `${THIS_YEAR}-${String(THIS_MONTH).padStart(2, '0')}-10`,
    note: 'Monthly billing due',
    is_paid: false,
    paid_payment_id: null,
    created_at: new Date(THIS_YEAR, THIS_MONTH - 1, 1).toISOString(),
    updated_at: new Date(THIS_YEAR, THIS_MONTH - 1, 1).toISOString(),
  },
]

